{
  parserClass     = 'com.pehrs.vespa.yql.plugin.YqlParser'
  // parserUtilClass = "com.pehrs.vespa.yql.plugin.psi.YqlParserUtil"
  psiPackage      = 'com.pehrs.vespa.yql.plugin.psi'
  psiImplPackage  = 'com.pehrs.vespa.yql.plugin.psi.impl'

  psiClassPrefix = "Yql"
  psiImplClassSuffix="Impl"
  // psiVisitorName = "YqlElementVisitor"
  elementTypeHolderClass = 'com.pehrs.vespa.yql.plugin.YqlElementTypes'
  elementTypeClass =       'com.pehrs.vespa.yql.plugin.YqlElementType'
  // psiImplUtilClass = 'com.pehrs.vespa.yql.plugin.psi.impl.YqlPsiImplUtils'
  tokenTypeClass = 'com.pehrs.vespa.yql.plugin.YqlTokenType'

  // implements("value") = "com.pehrs.vespa.yql.plugin.psi.YqlElement"
  // extends("value") = "com.pehrs.vespa.yql.plugin.psi.impl.YqlElementImpl"
  extends = "com.pehrs.vespa.yql.plugin.psi.impl.YqlElementImpl"

  tokens = [
          L_CURLY='{'
          R_CURLY='}'
          L_BRACKET='['
          R_BRACKET=']'

          COMMA=','
          COLON=':'

          TRUE='true'
          FALSE='false'
          NULL='null'
  ]
}

yql ::= item_*

// private item_ ::= (property|COMMENT|CRLF)
private item_ ::= (object)

object ::= '{' (object_element)* '}'


private object_element ::= property (','|&'}') {
  recoverWhile = not_brace_or_next_value
  pin = 1
}

array ::= '[' array_element* ']' {
  pin=1
}

private array_element ::= property_value (','|&']') {
  recoverWhile = not_bracket_or_next_value
  pin=1
}


string_value ::= IDENTIFIER | NUMBER | STRING

string_literal ::= DOUBLE_QUOTE string_value* DOUBLE_QUOTE

property_value ::= object | array | string_literal | NUMBER

property_key ::= string_literal

property ::= property_key ':' property_value

